import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/components/navbar/navbar";
import Footer from "@/src/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Logistic Bussiness App",
  description: "Generated by logistics bussiness app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="">
          <Navbar />
          <section className="relative min-h-screen">{children}</section>
          <Footer />
        </main>
      </body>
    </html>
  );
}
